People = {
"Homelander",
"SpongeBob",
"Will Smith",
"Curious George",
"Joker",
"Shrek",
"Andrew Tate",
"Patrick",
"Sandy",
"Mr.Krabs",
"Plankton",
"Chinese Eggman",
"Saul Goodman / Jimmy McGill",
"Andrew Garfield",
"Tobey Maguire",
"Tom Holland",
"Finger / Mike Ehrmantraut",
"Gustavo Fring",
"Jesse Pinkman",
"Walter White",
"Dora",
"Michael Morbious",
"Spy from TF2",

}
return People