People = {
"Homelander",
"SpongeBob SquarePants",
"Will Smith",
"Curious George",
"Joker",
"Shrek",
"Andrew Tate",
"Patrick Star",
"Sandy Cheeks",
"Eugene Krabs",
"Sheldon Plankton",
"Chinese Eggman",
"Saul Goodman / Jimmy McGill",
"Andrew Garfield",
"Tobey Maguire",
"Tom Holland",
"Finger / Mike Ehrmantraut",
"Gustavo Fring",
"Jesse Pinkman",
"Walter White",
"Dora",
"Michael Morbious",
"Spy from TF2",
"superman",
"batman",
"Bill nye",
"Black Bolt",
"Peter Griffin",
"Frog man",
"Cuphead",
"Mugman",
"Grug",
"Tim Lockwood",
"Palpatine",
"Sonic the hedgehog",
"waluigi",
"Talking Ben",
"Deadpool",
"Morshu",
"The Hulk",
"She-Hulk",
"Markiplier",
"Stewie Griffin",
"Thor",

}
return People