People = {
"Homelander",
"SpongeBob SquarePants",
"Will Smith",
"Curious George",
"Joker",
"Shrek",
"Andrew Tate",
"Patrick Star",
"Sandy Cheeks",
"Eugene Krabs",
"Sheldon Plankton",
"Chinese Eggman",
"Saul Goodman / Jimmy McGill",
"Andrew Garfield",
"Tobey Maguire",
"Tom Holland",
"Finger / Mike Ehrmantraut",
"Gustavo Fring",
"Jesse Pinkman",
"Walter White",
"Dora",
"Michael Morbious",
"Spy from TF2",
"superman",
"batman",
"Bill nye",
"Black Bolt",
"Peter Griffin",
"Frog man",
"Cuphead",
"Mugman",
"Grug",
"Tim Lockwood",
"Palpatine",
"Sonic the hedgehog",
"waluigi",
"Talking Ben",
"Deadpool",
"Morshu",
"The Hulk",
"She-Hulk",
"Markiplier",
"Stewie Griffin",
"Thor",
"Jason Vorhees",
"Freddy Kreuger",
"Freddy Fazbear",
"Ghostrider",
"Ghostface",
"Predator",
"Alien",
"SCP(your choice)",
"Dracula",
"Frankenstein's Monster",
"The Wolf Man",
"Gizmo the gremlin",
"Leatherface",
"Mummy",
"Chucky",
"Carnage",
"Invisible Man",
"Slappy from Goosebumps",
"Patrick Bateman",
"Pyramid Head",
"Leaprechaun",
"Carrie",
"Moon Knight",
"Leatherface",
"Mario",
"Luigi",
"Princess Peach",
"Princess Daisy",
"Bowser",
"Bowser Jr",
"Thanos",
"Harley Quinn",
"Cristiano Ronaldo",
"KSI",
"Logan Paul",
"Cardi B",
"Steve Harvey",
"Elon Musk",
"Mr. Bean",
"Snoop Dogg",
"Butcher",
"Johnny Depp",
"Jacksepticeye",
"a monke",
"Pikachu",
"ishowspeed",
"dancing roach",
"baby yoda",
"Darth Vader ",
"Rick Astley",
"NFT monke",
"big nose Spider-Man",
"XCMSHOW",
"Daredevil",
"a cat",
"doge",
"a shark",
"Scarlet witch",
"a Discord mod",
"a Twitch streamer",
"a news announcer",
"Captain America",
"Captain underpants",
"Iron man",
"Punisher",
"LETS GOOOOOOOOOOOOOO ball",
"a spooky skeleton",
"a furry",
"the minions",
"Gru",
"Amogus",
"Optimus prime",
"Bumblebee the transformer",
"Barry B. Benson",
"Juan the horse",
"the lawyer from the Bee Movie",
"Mysterio",
"Shadow the hedgehog",
"Tails the fox",
"Knuckles the echidna",
"Man-thing",
"Eminem",
"She-Hulk",
"the Demogorgon",
"Eleven from stranger things",
"Gus Fring",
"Korg from Thor",
"Zeus",
"Kratos",
"Howard Hamlin",
"Smelvin",
"a Leviathan from Subnautica",
"Miles Morales",
"the little mermaid",
"Amber Heard",
"Aquaman",
"Cyborg",
"The teen titans",
"Charizard",
"Greg from diary of a wimpy kid",
"Pac man",
"America Chavez",
"Minecraft Steve",
"Dhar man",
"Peppa pig",
"Hello Kitty",
"A-train",
"The Deep",
"Ms. marvel",
"general Grevious",
"PVZ zombie",
"PVZ onion",
"clash Royale Bowler",
"Yoshi",
"the Koopalings",
"the Flash",
"Hawk man",
"Green lantern",
"Black widow",
"Japanese Spider-Man",
"Mammot from my singing monsters",
"Furcorn from my singing monsters",
"Mister Fantastic",
"WONG",
"Jesus",
"Herbert",
"Senator Armstrong",
"Robbie rotten",
}
return People